version: '3.1'

services:
  nest_pg:
    image: postgres:15.1
    container_name: nest_pg
    restart: always
    env_file:
      - .env.development
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432